let suggestions = [
    "Austin",
    "Seattle",
    "San Francisco",
    "Washington",
    "Dallas",
    "Raleigh",
    "Los Angeles",
    "Atlanta",
    "Baltimore",
    "Boston",
    "Phoenix",
    "San Diego",
    "Houston",
    "Denver",
    "Colorado Springs",
    "New York",
    "Las Vegas",
    "Tampa",
    "Chicago",
    "Columbus",
    "Orlando",
    "Kansas City",
    "Minneapolis",
    "Portland",
    "Pittsburgh",
    "San Antonio",
    "Indianapolis",
    "Miami",
    "Philadelphia"
];